name: NPM Update

on:
  schedule:
  - cron: 0 0 * * * 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm dependencies update
      run: |
        git config --global user.email "github@jumoog.io" 
        git config --global user.name "Kilian von Pflugk"
        git remote rm origin
        git remote add origin "https://CI:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY"
        git checkout -b master
        npm install -g npm-check-updates
        ncu -u -s
        npm install --ignore-scripts
        git add package.json
        git add package-lock.json
        git diff-index --quiet HEAD || git commit -m "NPM Update [skip ci]"
        git push origin master --quiet
      env:
        CI: true
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      if: |
        contains(github.event.commits[0].message, '[skip ci]') == false &&
        contains(github.event.commits[0].message, '[ci skip]') == false
